### PR TITLE
Updated API Version to v8

### PR DESCRIPTION
**Pull request by GianC-Dev**

### CODE REVIEW

**Comment by key2peace** [comment]
we already have a full v8 tree in here, and just changing the api version itself ain't good enough either, checkout https://github.com/teamreflex/DiscordPHP/tree/feature/gateway_v8

**Comment by GianC-Dev** [comment]
No, that is enough. v8 only needs a intents. But added new props. If you want an add props, that is a not enough for you.

**Comment by key2peace** [comment]
feast your eyes on https://discord.com/developers/docs/change-log#api-and-gateway-v8 please

**Comment by davidcole1340** [comment]
As @key2peace posted above, version 8 is a breaking change and we can't drop it in, I've been working on a conversion on the `feature/gateway_v8` branch but it isn't ready nor stable yet.

**Comment by GianC-Dev** [comment]
> feast your eyes on https://discord.com/developers/docs/change-log#api-and-gateway-v8 please

It doesn't concern me if you don't understand what I'm saying and you are stupid. I'm sayed **If you want an add props, that is a not enough for you.**. If you want update to gateway version 8, only requires "intents" json param.

**Comment by key2peace** [comment]
so you waste your time working on something that has already been worked on and ignore everything I said about the mistakes you made and think you are right? who's the stupid one here? Have you even TRIED your code in the long run?

**Comment by davidcole1340** [comment]
Please don't come back to this repo if you are going to talk like that

**Pull request closed without merging**
