### PR TITLE
Change it a bit so it is somewhat friendly to newcomers ^^

### PR DESCRIPTION
**Pull request by acdenisSK**
*as the title says* You can also change it too, cause even my spelling can sometimes be bad too *shrug*

### CODE REVIEW

**Comment by acdenisSK** [comment]
you can also just ignore this pull request all together and make your own "How to install","troubleshooting" :wink:

**Comment by uniquoooo** [comment]
Thanks! Are you able to run PHP-CS-Fixer on it before I merge?

Also, could you say that `symfony/var-dumper` is optional?

**Comment by acdenisSK** [comment]
added the line `//optionial!` for var-dumper :wink: also used PHP-CS-FIXER and it throw no errors.

**Comment by uniquoooo** [comment]
Are you able to clean up the "Contributing" section? It seemed to mess up.

**Comment by acdenisSK** [comment]
Ok i think i fixed both the line `//optional!` (was red and i didn't want it there :P) and the messed up `contributing` idk what happended lol

**Comment by acdenisSK** [comment]
*so people know where to contribute*

**Comment by uniquoooo** [comment]
Thanks!

**Pull request merged**
